version: 2
jobs:
  build:
    working_directory: /home/cbgeo/research/lbm-dem
    docker:
      - image: quay.io/cbgeo/lbmdem
    steps:
      - checkout
      # GCC 6.3
      - run:
          name: GCC-6 build
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On .. 
            make clean && make -j8 
            ./lbmdemtest
      # GCC 3.9
      - run:
          name: Clang-3.9 build
          command: |
            ls
            cd build && rm -rf ./*
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On .. 
            make clean && make -j8 
            ./lbmdemtest
